### ISSUE TITLE
New site generator to replace my suspended heavy WordPress site

### ISSUE THREAD

**Issue by qiansen1386** [qiansen1386/qiansen1386.github.io#3]
### TODO of phase 1:###

- [x] Delete old website files
- [x] Setup New Hugo Site
- [x] Install a Theme
- [x] Disqus/多说
- [x] Setup Google Analytic
- [x] Create git-submodule in order to proper separate Source and generated files
- [x] Automated deployments with Wercker
- [x] Use relative URLs

Phase 2:
See #4

**Comment by qiansen1386** [comment]
refer to bf1d192f384cd5648bec1a85519d92d78ae40424

**Comment by qiansen1386** [comment]
Phase 1.1:

- [ ] Fix the theme
Phase 2:
(To be Confirmed)

- [ ] Bilingual support=> Make sure the Chinese version can go though GFW. However, It would be such an honor if I I can't :joy::joy::joy:
- [ ] Tune the existing theme / Create a brand new theme using Vue.js/Angular2

**Comment by qiansen1386** [comment]
Considered completed
