### ISSUE TITLE
phase 1.1 & 2 goals

### ISSUE THREAD

**Issue by qiansen1386** [qiansen1386/qiansen1386.github.io#4]
### Phase 1.1:###

- [x] Change to a new Theme as the base
- [x] Custom the theme as needs
- [x] Improve the styles

### Phase 2:###
(To be Confirmed)

- [ ] ~~Bilingual support=> Make sure the Chinese version can go though GFW. However, It would be such an honor if I I can't :joy::joy::joy:~~
- [x] Tune the existing theme / Create a brand new theme using ~~Vue.js/Angular2~~ SCSS / PostCSS + a dark color scheme like https://bootswatch.com/cyborg/ but try the best choose form Base-16 Color
